apiVersion: apps/v1
kind: Deployment
metadata:
  name: galvr-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: galvr-nextjs
  template:
    metadata:
      labels:
        run: galvr-nextjs
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: 'false'
    spec:
      containers:
        - name: galvr-nextjs
          image: galvr-nextjs
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: galvr-nextjs
spec:
  type: NodePort
  selector:
    run: galvr-nextjs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
