opentelemetry-collector:
  config:
    processors:
      batch/2:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlphttp/example:
        endpoint: http://metricendpoint:3000
        tls:
          insecure: true
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch/2]
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, filter/ottl, transform, batch/2]
          exporters: [otlphttp/example]

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
