apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    exporters:
      logging: 
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true
      otlphttp:
        endpoint: http://todo-metricendpoint:3000
        tls: 
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp]
      telemetry:
        logs:
          level: "debug"
