apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        selector: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
      #     args: ['--dbpath', '/data/db']
      #     volumeMounts:
      #       - name: 'mongo-data-dir'
      #         mountPath: '/data/db'
      # volumes:
      #   - name: 'mongo-data-dir'
      #     persistentVolumeClaim:
      #       claimName: 'pvc'
