apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricendpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metricendpoint
  template:
    metadata:
      labels:
        run: metricendpoint
    spec:
      containers:
        - name: metricendpoint
          image: metricendpoint
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: metricendpoint
spec:
  selector:
    run: metricendpoint
  ports:
    - port: 3000
      targetPort: 3000
